baseurl = "https://msagca.github.io/"
languageCode = "en-us"
title = "msagca"
defaultContentLanguage = "en"
hasCJKLanguage = false
[pagination]
pagerSize = 24
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
tag = "tags"
