title: msagca
author: Mustafa Said Ağca
url: https://msagca.github.io/
baseurl: /
permalink: /:title
favicon: logo.svg
remote_theme: riggraz/no-style-please
theme_config:
  appearance: auto
  back_home_text: '..'
  date_format: '%Y-%m-%d'
  show_description: false
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
