title: msagca
baseurl: ''
permalink: /:title
description: ''
show_excerpts: true
paginate: 1
dash:
  date_format: "%b %-d, %Y"
  disqus:
    shortname: msagca
  social_links:
    - url: https://linkedin.com/in/msagca
      icon: linkedin
      color: indigo
    - url: https://github.com/msagca
      icon: github
      color: purple
  show_author: false
  animation_speed: 50
  rtl: false
remote_theme: bitbrain/jekyll-dash
