source "https://rubygems.org"
gem "bundler"
gem "font-awesome-sass"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-tagging"
gem "jekyll"
gem "logger"
gem "rouge"
gem "wdm" if Gem.win_platform?